/**
 *---------------------------------------------------------------------------
 * @brief    A minimal example blinking LED on Raspberry Pi Pico (RP2040) using direct register access in C.
 *
 * @file     main.c
 * @author   Peter Malmberg <peter.malmberg@gmail.com>
 * @version  0.01
 * @date     2026-04-01
 * @license  MIT
 *
 *---------------------------------------------------------------------------
 *
 *
 */

// Include ------------------------------------------------------------------

#include "main.h"

// Macros -------------------------------------------------------------------


// Prototypes ---------------------------------------------------------------


// Datatypes ----------------------------------------------------------------


// Variables ----------------------------------------------------------------


// Code ---------------------------------------------------------------------

#include <stdint.h>

// RP2040 register definitions (from datasheet)
#define RESETS_BASE         0x4000c000u
#define RESETS_RESET        (*(volatile uint32_t*)(RESETS_BASE + 0x00))
#define RESETS_RESET_DONE   (*(volatile uint32_t*)(RESETS_BASE + 0x08))

#define SIO_BASE            0xd0000000u
#define SIO_GPIO_OUT_SET    (*(volatile uint32_t*)(SIO_BASE + 0x14))
#define SIO_GPIO_OUT_CLR    (*(volatile uint32_t*)(SIO_BASE + 0x18))
#define SIO_GPIO_OE_SET     (*(volatile uint32_t*)(SIO_BASE + 0x24))

#define IO_BANK0_BASE       0x40014000u
#define GPIO_CTRL_OFFSET    0x04        // each GPIO has 8-byte struct
#define IO_BANK0_GPIO25_CTRL (*(volatile uint32_t*)(IO_BANK0_BASE + 25*8 + GPIO_CTRL_OFFSET))

#define PADS_BANK0_BASE     0x4001c000u
#define PADS_BANK0_GPIO25   (*(volatile uint32_t*)(PADS_BANK0_BASE + 0x68))  // GPIO25 offset

#define LED_PIN             25

// Simple busy-wait delay (not precise, but good enough for blinking)
static void delay(uint32_t count) {
    for (uint32_t i = 0; i < count; i++) {
        __asm__ volatile("nop");
    }
}

/**
 * Code generated by Grook
 */
static int main_grook(void) {
    // Take IO_BANK0 and PADS_BANK0 out of reset
    RESETS_RESET &= ~(1u << 5);   // IO_BANK0
    RESETS_RESET &= ~(1u << 8);   // PADS_BANK0
    while ((RESETS_RESET_DONE & (1u << 5)) == 0);  // wait IO_BANK0
    while ((RESETS_RESET_DONE & (1u << 8)) == 0);  // wait PADS_BANK0

    // Configure GPIO25 as SIO (GPIO) function
    IO_BANK0_GPIO25_CTRL = 5u;    // FUNCSEL = 5 (SIO)

    // Enable output on GPIO25
    SIO_GPIO_OE_SET = (1u << LED_PIN);

    // Optional: drive strength / pull (default is usually fine)
    PADS_BANK0_GPIO25 = 0x70u;    // standard value (no pull, etc.)

    while (1) {
        // LED ON
        SIO_GPIO_OUT_SET = (1u << LED_PIN);
        delay(400000);   // ~0.5s at ~125MHz (rough)

        // LED OFF
        SIO_GPIO_OUT_CLR = (1u << LED_PIN);
        delay(400000);
    }
    return 0;
}

// Copyright (c) 2023 CarlosFTM
// This code is licensed under MIT license (see LICENSE.txt for details)
#define PUT32(address, value) (*((volatile unsigned int*)address)) = value
#define GET32(address) *(volatile unsigned int*)address

static int main_carlos(void) {
    PUT32(0x4000f000, (1 << 5));  // IO BANK

    while (GET32(0x4000c008) & (1 << 5) == 0);  // Reset Done?

    PUT32(0x400140cc, 0x05);       // IO PAD = FUNC 5 (GPIO)
    PUT32(0xd0000020, (1 << 25));  // GPIO_OE

    while (1) {
        PUT32(0xd000001c, (1 << 25));  // XOR GPIO
        for (volatile unsigned int a = 90000; a > 0; a--);
    }

    return 0;
}

int main(void) {
    //main_grook();
    main_carlos();
}