#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------------
#
# GTK demo for Python
#
# File:     gdemo
# Author:   Peter Malmberg  <peter.malmberg@gmail.com>
# Org:      __ORGANISTATION__
# Date:     2024-07-30
# License:
# Python:   >= 3.0
#
# ----------------------------------------------------------------------------
#
# https://python-gtk-3-tutorial.readthedocs.io/en/latest/introduction.html

import traceback
import os
import sys
import logging
import argparse

import gi

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk


class App:
    NAME = "gdemo"
    VERSION = "0.01"
    DESCRIPTION = "gtk demo for python"
    LICENSE = ""
    AUTHOR = "Peter Malmberg"
    EMAIL = "<peter.malmberg@gmail.com>"
    ORG = "__ORGANISATION__"
    HOME = ""
    ICON = ""


class Demo(Gtk.Widget):
    def __init__(self) -> None:
        super().__init__()

        layout = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL)
        self.add(layout)
        layout.add(Gtk.Label(label="Label 1"))
        layout.add(Gtk.Label(label="Label 2"))


class MainWindow(Gtk.Window):
    def __init__(self):
        super().__init__(title="Hello World")

        self.set_border_width(2)
        self.set_default_size(400, 200)

        self.box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        self.add(self.box)

        self.button = Gtk.Button(label="Click Here")
        self.button.connect("clicked", self.on_button_clicked)

        self.box.add(self.button)

        label = Gtk.Label(label="Normal")
        self.box.add(label)
        label2 = Gtk.Label(label="<b>Normal</b>")
        label2 = Gtk.Label()
        label2.set_markup("<b><i>Normal</i></b>")
        self.box.add(label2)
        # self.box.add(Demo())

    def on_button_clicked(self, widget):
        print("Hello World")


def main() -> None:
    logging_format = "[%(levelname)s] %(lineno)-4d %(funcName)-14s : %(message)s"
    #    logging.basicConfig(format=logging_format, level=logging.DEBUG)

    parser = argparse.ArgumentParser(
        prog=App.NAME, description=App.DESCRIPTION, epilog="", add_help=True
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"{App.NAME} {App.VERSION}",
        help="Print version information",
    )

    parser.add_argument(
        "--debug", action="store_true", default=False, help="Print debug messages"
    )

    args = parser.parse_args()

    if args.debug:
        logging.basicConfig(format=logging_format, level=logging.DEBUG)

    win = MainWindow()
    win.connect("destroy", Gtk.main_quit)
    win.show_all()
    Gtk.main()


if __name__ == "__main__":
    try:
        main()
        sys.exit(0)
    except KeyboardInterrupt as e:  # Ctrl-C
        raise e
    except SystemExit as e:  # sys.exit()
        raise e
    except Exception as e:
        print("ERROR, UNEXPECTED EXCEPTION")
        print(str(e))
        traceback.print_exc()
        os._exit(1)
