#!/usr/bin/env bash
# shellcheck disable=2034
# shellcheck disable=1090
#---------------------------------------------------------------------
#
#  tut_string2
#
#  [Description]
#    Test of strings
#
#  [Author]
#    Peter Malmberg <peter.malmberg@gmail.com>
#
#  [Date]
#    2022-07-29
#
#  [License]
#    MIT
#
#---------------------------------------------------------------------
# Generated with bashplates. [https://github.com/zonbrisad/bashplates]
#---------------------------------------------------------------------
#

#set -o xtrace   # Display commands as they are executed
#set -o pipefail # Exit script when pipe fails

# Directory where script is located
scriptPath=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

#---------------------------------------------------------------------

# Initiate string
S="Hello World"

# Initiate array of strings
#SA=($S)

prints() {
  printf "%-20s  %s\n" "$1" "$2"
}

# prints "1232" "asdf"
prints "String:" "${S}"
prints "String length:" "${#S}"
prints "Substring:" "${S:0:5}"
prints "Remove:" "${S/World/}"
prints "Replace one:" "${S/World/Europe}"
# prints "Replace all:" "${S//World/Europe}"
prints "Remove begining:" "${S#Hello }"
prints "Remove end:" "${S%World}"

# echo -e "\nArray tests ----------"
# echo ${SA[@]}
# echo ${SA[@]:1}
# for i in "${SA[@]}"; do
# echo $i
# done
