#!/usr/bin/env bash
# shellcheck disable=2034
# shellcheck disable=1090
#---------------------------------------------------------------------
#
#  tut_string2
#
#  [Description]
#    Test of strings
#
#  [Author]
#    Peter Malmberg <peter.malmberg@gmail.com>
#
#  [Date]
#    2022-07-29
#
#  [License]
#    MIT
#
#---------------------------------------------------------------------
# Generated with bashplates. [https://github.com/zonbrisad/bashplates]
#---------------------------------------------------------------------
#

#set -o xtrace   # Display commands as they are executed
#set -o pipefail # Exit script when pipe fails

# Directory where script is located
scriptPath=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#---------------------------------------------------------------------

# Initiate string
S="Hello World everybody in the World"

# Initiate array of strings
SA=($S)


echo -e "String tests --------"
echo -e "String:\n${S}"
echo -e "String length:\n${#S}"
echo -e "Substring:\n${S:0:5}"

echo -e "Remove:\n${S/World }"
echo -e "Replace one:\n${S/World/Europe}"
echo -e "Replace all:\n${S//World/Europe}"

echo -e "Remove begining:\n${S#Hello }"
echo -e "Remove end:\n${S%World}"


echo -e "\nArray tests ----------"
echo ${SA[@]}
echo ${SA[@]:1}
for i in "${SA[@]}"; do
  echo $i
done	
