#!/usr/bin/env bash
# shellcheck disable=2034
# shellcheck disable=1090
#---------------------------------------------------------------------
#
#  tut_array
#
#  [Description]
#    Tutorial of sed
#
#  [Author]
#    Peter Malmberg <peter.malmberg@gmail.com>
#
#  [Date]
#    2022-11-13
#
#  [License]
#    MIT
#
#---------------------------------------------------------------------
# Generated with bashplates. [https://github.com/zonbrisad/bashplates]
#---------------------------------------------------------------------
#

#set -o xtrace   # Display commands as they are executed
#set -o pipefail # Exit script when pipe fails

# Directory where script is located
#scriptPath=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

#---------------------------------------------------------------------
#  Links
#
# https://www.baeldung.com/linux/file-insert-multiple-lines
# https://fabianlee.org/2018/10/28/linux-using-sed-to-insert-lines-before-or-after-a-match/
# https://linuxhint.com/how_to_insert_a_line_after_the_match_using_sed/
# https://www.grymoire.com/Unix/Sed.html
#
#---------------------------------------------------------------------

ef=sed-test

efile() {
  rm -f "$ef"
  {
    echo "Row 1"
    echo "Row 2"
    echo "Row 3"
    echo "Row 4"
    echo "Row 5"
    echo "Row 6"
    echo "Row 7"
    echo "Row 9"
    echo "Row 10"
    echo "To be deleted"
    echo "Row 11"

  } \
    >>"$ef"
}

IFS=$' '

efile

# Append line at end of file
sed -i "$ a String added after last row of file" "$ef"

# Append line after row 7
sed -i "7 a Row 8 Added afterwards" "$ef"

# Add string after match
sed -i "s/Row 2/& String added after match/" "$ef"

# Append line after match
sed -i "/Row 3/a String added on line after match" "$ef"

# Append line before match
sed -i "/Row 7/i String added on line before match" "$ef"

# Replace row
sed -i "s/Row 5/String replaced row/" "$ef"

# Replace text to uppercase
#sed -i "y/Row"

# Delete row
sed -i "/To be/d" "$ef"

# Append text from piple after match
echo -e "Extra 1\nExtra 2\nExtra 3" | sed -i "/Row 10/r /dev/stdin" "$ef"

echo
cat $ef
